# Generated by Django 6.1 on 2026-08-18 00:01

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clinica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120, unique=True, verbose_name='nombre')),
                ('creada', models.DateTimeField(default=django.utils.timezone.now, verbose_name='creada')),
            ],
            options={
                'verbose_name': 'Clínica',
                'verbose_name_plural': 'Clínicas',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Sede',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120, verbose_name='nombre')),
                ('direccion', models.CharField(blank=True, max_length=250, verbose_name='dirección')),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sedes', to='tenancy.clinica', verbose_name='Clínica')),
            ],
            options={
                'verbose_name': 'Sede',
                'verbose_name_plural': 'Sedes',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='correo')),
                ('nombre', models.CharField(max_length=120, verbose_name='nombre')),
                ('apellidos', models.CharField(blank=True, max_length=120, verbose_name='apellidos')),
                ('rol', models.CharField(choices=[('veterinario', 'veterinario'), ('recepcion', 'recepción'), ('admin', 'admin')], default='recepcion', max_length=20, verbose_name='rol')),
                ('is_active', models.BooleanField(default=True, verbose_name='activo')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='alta')),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuarios', to='tenancy.clinica', verbose_name='Clínica')),
                ('sedes', models.ManyToManyField(blank=True, related_name='usuarios', to='tenancy.sede', verbose_name='Sedes')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
                'ordering': ['apellidos', 'nombre'],
            },
        ),
        migrations.AddConstraint(
            model_name='sede',
            constraint=models.UniqueConstraint(fields=('clinic', 'nombre'), name='sede_unica_en_la_clinica'),
        ),
    ]
