# Generated by Django 6.1 on 2026-08-25 19:28

import apps.campos
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenancy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClinicaDeDerivacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120, verbose_name='nombre')),
                ('telefono', apps.campos.CampoDeTelefono(blank=True, max_length=16, verbose_name='teléfono')),
                ('direccion', models.CharField(blank=True, max_length=250, verbose_name='dirección')),
            ],
            options={
                'verbose_name': 'Clínica de derivación',
                'verbose_name_plural': 'Clínicas de derivación',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='ExcepcionDeAtencion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(verbose_name='fecha')),
                ('motivo', models.CharField(blank=True, max_length=120, verbose_name='motivo')),
                ('desde', models.TimeField(blank=True, null=True, verbose_name='desde')),
                ('hasta', models.TimeField(blank=True, null=True, verbose_name='hasta')),
            ],
            options={
                'verbose_name': 'Excepción de atención',
                'verbose_name_plural': 'Excepciones de atención',
                'ordering': ['sede', 'fecha', 'desde'],
            },
        ),
        migrations.CreateModel(
            name='FranjaDeAtencion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.SmallIntegerField(choices=[(0, 'lunes'), (1, 'martes'), (2, 'miércoles'), (3, 'jueves'), (4, 'viernes'), (5, 'sábado'), (6, 'domingo')], verbose_name='día')),
                ('desde', models.TimeField(verbose_name='desde')),
                ('hasta', models.TimeField(verbose_name='hasta')),
            ],
            options={
                'verbose_name': 'Franja de atención',
                'verbose_name_plural': 'Franjas de atención',
                'ordering': ['sede', 'dia', 'desde'],
            },
        ),
        migrations.AddField(
            model_name='sede',
            name='atiende_urgencias',
            field=models.BooleanField(default=False, verbose_name='atiende urgencias'),
        ),
        migrations.AddField(
            model_name='sede',
            name='telefono_de_urgencias',
            field=apps.campos.CampoDeTelefono(blank=True, max_length=16, verbose_name='teléfono de urgencias'),
        ),
        migrations.AddConstraint(
            model_name='sede',
            constraint=models.CheckConstraint(condition=models.Q(('telefono_de_urgencias', ''), ('atiende_urgencias', True), _connector='OR'), name='solo_una_sede_de_urgencias_tiene_telefono_de_urgencias'),
        ),
        migrations.AddField(
            model_name='clinicadederivacion',
            name='clinic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s', to='tenancy.clinica', verbose_name='Clínica'),
        ),
        migrations.AddField(
            model_name='excepciondeatencion',
            name='clinic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s', to='tenancy.clinica', verbose_name='Clínica'),
        ),
        migrations.AddField(
            model_name='excepciondeatencion',
            name='sede',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='excepciones', to='tenancy.sede', verbose_name='Sede'),
        ),
        migrations.AddField(
            model_name='franjadeatencion',
            name='clinic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s', to='tenancy.clinica', verbose_name='Clínica'),
        ),
        migrations.AddField(
            model_name='franjadeatencion',
            name='sede',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='franjas', to='tenancy.sede', verbose_name='Sede'),
        ),
        migrations.AddConstraint(
            model_name='clinicadederivacion',
            constraint=models.UniqueConstraint(fields=('clinic', 'nombre'), name='clinica_de_derivacion_unica_en_la_clinica'),
        ),
        migrations.AddConstraint(
            model_name='excepciondeatencion',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('desde__isnull', True), ('hasta__isnull', True)), models.Q(('desde__isnull', False), ('hasta__isnull', False)), _connector='OR'), name='una_excepcion_tiene_las_dos_horas_o_ninguna'),
        ),
        migrations.AddConstraint(
            model_name='excepciondeatencion',
            constraint=models.CheckConstraint(condition=models.Q(('hasta__isnull', True), ('hasta__gt', models.F('desde')), _connector='OR'), name='una_excepcion_termina_despues_de_empezar'),
        ),
        migrations.AddConstraint(
            model_name='franjadeatencion',
            constraint=models.CheckConstraint(condition=models.Q(('hasta__gt', models.F('desde'))), name='una_franja_termina_despues_de_empezar'),
        ),
        migrations.AddConstraint(
            model_name='franjadeatencion',
            constraint=models.UniqueConstraint(fields=('sede', 'dia', 'desde'), name='una_franja_por_sede_dia_y_hora_de_apertura'),
        ),
    ]
