# Generated by Django 6.1 on 2026-08-27 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenancy', '0002_configuracion_de_la_sede'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinica',
            name='cerrada',
            field=models.DateTimeField(blank=True, null=True, verbose_name='cerrada'),
        ),
    ]
