# Generated by Django 6.1 on 2026-08-18 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenancy', '0001_initial'),
        ('tutors', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tutor',
            options={'ordering': ['apellidos', 'nombre'], 'verbose_name': 'Tutor', 'verbose_name_plural': 'Tutores'},
        ),
        migrations.AddField(
            model_name='tutor',
            name='apellidos',
            field=models.CharField(blank=True, max_length=200, verbose_name='apellidos'),
        ),
        migrations.AddField(
            model_name='tutor',
            name='direccion',
            field=models.CharField(blank=True, max_length=250, verbose_name='dirección'),
        ),
        migrations.AddField(
            model_name='tutor',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='correo'),
        ),
        migrations.AddIndex(
            model_name='tutor',
            index=models.Index(fields=['clinic', 'apellidos', 'nombre'], name='tutor_por_apellidos'),
        ),
    ]
