# Generated by Django 6.1 on 2026-08-23 05:01

import apps.tutors.campos
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenancy', '0001_initial'),
        ('tutors', '0002_datos_de_contacto'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutor',
            name='rut',
            field=apps.tutors.campos.CampoDeRut(blank=True, max_length=9, verbose_name='RUT'),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='telefono',
            field=apps.tutors.campos.CampoDeTelefono(blank=True, max_length=16, verbose_name='teléfono'),
        ),
        migrations.AddConstraint(
            model_name='tutor',
            constraint=models.UniqueConstraint(condition=models.Q(('rut', ''), _negated=True), fields=('clinic', 'rut'), name='rut_unico_dentro_de_la_clinica'),
        ),
    ]
