# Generated by Django 6.1 on 2026-08-23 23:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_paciente'),
        ('tenancy', '0001_initial'),
        ('tutors', '0003_rut_y_telefono'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vinculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('responsable', models.BooleanField(default=False, verbose_name='es el responsable')),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s', to='tenancy.clinica', verbose_name='Clínica')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vinculos', to='patients.paciente', verbose_name='Paciente')),
                ('tutor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vinculos', to='tutors.tutor', verbose_name='Tutor')),
            ],
            options={
                'verbose_name': 'Vínculo',
                'verbose_name_plural': 'Vínculos',
                'ordering': ['-responsable', 'tutor__apellidos', 'tutor__nombre', 'pk'],
            },
        ),
        migrations.AddField(
            model_name='tutor',
            name='pacientes',
            field=models.ManyToManyField(related_name='tutores', through='tutors.Vinculo', to='patients.paciente', verbose_name='Pacientes'),
        ),
        migrations.AddConstraint(
            model_name='vinculo',
            constraint=models.UniqueConstraint(fields=('tutor', 'paciente'), name='un_solo_vinculo_por_tutor_y_paciente'),
        ),
        migrations.AddConstraint(
            model_name='vinculo',
            constraint=models.UniqueConstraint(condition=models.Q(('responsable', True)), fields=('paciente',), name='un_solo_tutor_responsable_por_paciente'),
        ),
    ]
