# Generated by Django 6.1 on 2026-08-24 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0003_estados_del_paciente'),
        ('tenancy', '0001_initial'),
        ('tutors', '0004_vinculo_con_el_paciente'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='vinculo',
            name='un_solo_vinculo_por_tutor_y_paciente',
        ),
        migrations.AddField(
            model_name='vinculo',
            name='fecha_de_cierre',
            field=models.DateField(blank=True, null=True, verbose_name='hasta'),
        ),
        migrations.AddConstraint(
            model_name='vinculo',
            constraint=models.UniqueConstraint(condition=models.Q(('fecha_de_cierre__isnull', True)), fields=('tutor', 'paciente'), name='un_solo_vinculo_abierto_por_tutor_y_paciente'),
        ),
        migrations.AddConstraint(
            model_name='vinculo',
            constraint=models.CheckConstraint(condition=models.Q(('responsable', False), ('fecha_de_cierre__isnull', True), _connector='OR'), name='un_vinculo_cerrado_no_es_responsable'),
        ),
    ]
