# Generated by Django 6.1 on 2026-08-25 22:15

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenancy', '0002_configuracion_de_la_sede'),
        ('tutors', '0005_cierre_del_vinculo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consentimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('canal', models.CharField(choices=[('whatsapp', 'WhatsApp'), ('telefono', 'teléfono'), ('correo', 'correo')], max_length=20, verbose_name='canal')),
                ('otorgado', models.BooleanField(verbose_name='autoriza')),
                ('fecha', models.DateField(default=django.utils.timezone.localdate, verbose_name='fecha')),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s', to='tenancy.clinica', verbose_name='Clínica')),
                ('tutor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consentimientos', to='tutors.tutor', verbose_name='Tutor')),
            ],
            options={
                'verbose_name': 'Consentimiento de contacto',
                'verbose_name_plural': 'Consentimientos de contacto',
                'ordering': ['-fecha', '-pk'],
                'indexes': [models.Index(fields=['tutor', 'canal', '-fecha', '-id'], name='consentimiento_ultimo')],
            },
        ),
    ]
