# Generated by Django 6.1 on 2026-09-28 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutors', '0006_consentimiento_de_contacto'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutor',
            name='anonimizado',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='anonimizado'),
        ),
    ]
