# Generated by Django 6.1 on 2026-09-29 04:42

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenancy', '0003_cierre_de_la_clinica'),
        ('tutors', '0007_anonimizacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Suprimido',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('por_el_rut', models.CharField(blank=True, max_length=64, verbose_name='huella del RUT')),
                ('por_el_nombre', models.CharField(blank=True, max_length=64, verbose_name='huella del nombre y el teléfono')),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s', to='tenancy.clinica', verbose_name='Clínica')),
            ],
            options={
                'verbose_name': 'Tutor suprimido',
                'verbose_name_plural': 'Tutores suprimidos',
            },
        ),
    ]
