# Generated by Django 6.1 on 2026-08-23 23:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenancy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='nombre')),
                ('especie', models.CharField(choices=[('perro', 'perro'), ('gato', 'gato'), ('conejo', 'conejo'), ('roedor', 'roedor'), ('ave', 'ave'), ('reptil', 'reptil'), ('huron', 'hurón')], max_length=20, verbose_name='especie')),
                ('raza', models.CharField(blank=True, max_length=120, verbose_name='raza')),
                ('sexo', models.CharField(blank=True, choices=[('macho', 'macho'), ('hembra', 'hembra')], max_length=10, verbose_name='sexo')),
                ('fecha_de_nacimiento', models.DateField(blank=True, null=True, verbose_name='fecha de nacimiento')),
                ('color', models.CharField(blank=True, max_length=80, verbose_name='color')),
                ('observaciones', models.TextField(blank=True, verbose_name='observaciones')),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s', to='tenancy.clinica', verbose_name='Clínica')),
            ],
            options={
                'verbose_name': 'Paciente',
                'verbose_name_plural': 'Pacientes',
                'ordering': ['nombre', 'pk'],
                'indexes': [models.Index(fields=['clinic', 'nombre'], name='paciente_por_nombre')],
            },
        ),
    ]
