# Generated by Django 6.1 on 2026-08-24 00:30

import apps.patients.campos
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_paciente'),
        ('tenancy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='estado_de_identificacion',
            field=models.CharField(blank=True, choices=[('sin_chip', 'sin chip'), ('implantado', 'chip implantado'), ('inscrito', 'inscrito en el Registro Nacional')], max_length=20, verbose_name='estado de identificación'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='microchip',
            field=apps.patients.campos.CampoDeMicrochip(blank=True, max_length=15, verbose_name='microchip'),
        ),
        migrations.AddIndex(
            model_name='paciente',
            index=models.Index(fields=['clinic', 'microchip'], name='paciente_por_microchip'),
        ),
        migrations.AddConstraint(
            model_name='paciente',
            constraint=models.UniqueConstraint(condition=models.Q(('microchip', ''), _negated=True), fields=('clinic', 'microchip'), name='microchip_unico_dentro_de_la_clinica'),
        ),
    ]
