# Generated by Django 6.1 on 2026-08-24 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_microchip_e_identificacion'),
        ('tenancy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='estado',
            field=models.CharField(choices=[('activo', 'activo'), ('inactivo', 'inactivo'), ('fallecido', 'fallecido')], default='activo', max_length=20, verbose_name='estado'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='fecha_de_fallecimiento',
            field=models.DateField(blank=True, null=True, verbose_name='fecha de fallecimiento'),
        ),
        migrations.AddConstraint(
            model_name='paciente',
            constraint=models.CheckConstraint(condition=models.Q(('fecha_de_fallecimiento__isnull', True), ('estado', 'fallecido'), _connector='OR'), name='solo_un_paciente_fallecido_tiene_fecha_de_fallecimiento'),
        ),
    ]
