# Generated by Django 6.1 on 2026-08-18 02:34

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenancy', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroDeAcceso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_de_objeto', models.CharField(max_length=100, verbose_name='tipo de objeto')),
                ('identificador', models.CharField(blank=True, max_length=64, verbose_name='identificador')),
                ('accion', models.CharField(choices=[('lectura', 'lectura'), ('creacion', 'creación'), ('modificacion', 'modificación')], max_length=20, verbose_name='acción')),
                ('momento', models.DateTimeField(default=django.utils.timezone.now, verbose_name='momento')),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s', to='tenancy.clinica', verbose_name='Clínica')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='accesos', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Registro de acceso',
                'verbose_name_plural': 'Registros de acceso',
                'ordering': ['-momento', '-pk'],
                'indexes': [models.Index(fields=['clinic', '-momento'], name='acceso_por_clinica_y_fecha'), models.Index(fields=['tipo_de_objeto', 'identificador'], name='acceso_por_objeto')],
            },
        ),
    ]
