# Generated by Django 6.1 on 2026-09-28 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0002_registro_inalterable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrodeacceso',
            name='accion',
            field=models.CharField(choices=[('lectura', 'lectura'), ('creacion', 'creación'), ('modificacion', 'modificación'), ('anonimizacion', 'anonimización')], max_length=20, verbose_name='acción'),
        ),
    ]
