# Generated by Django 6.1 on 2026-08-25 23:45

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenancy', '0002_configuracion_de_la_sede'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Importacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('que_se_importo', models.CharField(choices=[('tutores', 'Tutores')], max_length=20, verbose_name='qué se importó')),
                ('planilla', models.CharField(max_length=255, verbose_name='planilla')),
                ('momento', models.DateTimeField(default=django.utils.timezone.now, verbose_name='momento')),
                ('filas_leidas', models.PositiveIntegerField(default=0, verbose_name='filas leídas')),
                ('filas_creadas', models.PositiveIntegerField(default=0, verbose_name='filas creadas')),
                ('filas_repetidas', models.PositiveIntegerField(default=0, verbose_name='filas repetidas')),
                ('filas_con_error', models.PositiveIntegerField(default=0, verbose_name='filas con error')),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s', to='tenancy.clinica', verbose_name='Clínica')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='importaciones', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Importación',
                'verbose_name_plural': 'Importaciones',
                'ordering': ['-momento', '-pk'],
                'indexes': [models.Index(fields=['clinic', '-momento'], name='importacion_por_fecha')],
            },
        ),
    ]
