# Generated by Django 6.1 on 2026-08-26 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imports', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='importacion',
            name='que_se_importo',
            field=models.CharField(choices=[('tutores', 'Tutores'), ('pacientes', 'Pacientes')], max_length=20, verbose_name='qué se importó'),
        ),
    ]
